on:
  pull_request:
    branches:
      - master
      - dev

name: Test Extension
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Test
        run: npm run ui-test
