on:
  pull_request:
    branches:
      - master

name: Test Extension
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        version: ['1.71.0', 'latest'] # 1.71.0 is the minimum version supported by the extension
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Test OS ${{ matrix.os }} - VSCode ${{ matrix.version }}
        run: |
          npm run install:all
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          npm run ui-test -- --code_version ${{ matrix.version }}
