on:
  pull_request:
    branches:
      - master
      - dev

name: Test Extension
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        # os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Test
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          npm run ui-test
